quizops:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'db') }}"
      user: "{{ env_var('DB_USER', 'quiz') }}"
      password: "{{ env_var('DB_PASSWORD', 'quiz') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      dbname: "{{ env_var('DB_NAME', 'quizops') }}"
      schema: analytics